// Campaign data for demo
export const campaignData = {
  id: 1,
  name: "Spring 2023 Outreach",
  status: "Active",
  description: "This campaign targets procurement managers in manufacturing companies across the Midwest. The goal is to schedule product demos with at least 15 qualified leads.",
  channels: ["email", "linkedin", "call"],
  createdAt: "2023-03-15",
  leads: 150,
  responses: 42,
  contacted: 120,
  meetingsBooked: 12,
  targetResponses: 50,
  targetMeetings: 15,
  positive: 30,  // Added positive responses
  negative: 12,  // Added negative responses
  performance: [
    { date: "Mar 15", responses: 0 },
    { date: "Mar 16", responses: 3 },
    { date: "Mar 17", responses: 5 },
    { date: "Mar 18", responses: 8 },
    { date: "Mar 19", responses: 10 },
    { date: "Mar 20", responses: 15 },
    { date: "Mar 21", responses: 22 },
    { date: "Mar 22", responses: 28 },
    { date: "Mar 23", responses: 33 },
    { date: "Mar 24", responses: 38 },
    { date: "Mar 25", responses: 42 },
  ],
  teamMembers: ['John Smith', 'Sarah Lee', 'Alex Chen', 'Mia Johnson'],
  stages: [
    { id: 1, name: "Not Contacted", count: 24 },
    { id: 2, name: "Contacted", count: 15 },
    { id: 3, name: "Replied", count: 8 },
    { id: 4, name: "Follow-Up Needed", count: 5 },
    { id: 5, name: "Positive", count: 3 },
    { id: 6, name: "Negative", count: 2 },
  ]
};

// Mock leads data for the campaign
export const leadsData = [
  {
    id: 1,
    name: "Michael Cooper",
    company: "Industrials Inc",
    email: "mcooper@industrials.com",
    linkedin: "https://linkedin.com/in/michaelcooper",
    whatsapp: null,
    twitter: "@mcooper",
    instagram: null,
    facebook: null,
    status: "Contacted",
    lastContact: "2023-03-22",
    lastContacted: "2023-03-22",
    currentStage: "Contacted",
    assignedTo: "John Smith"
  },
  {
    id: 2,
    name: "Jennifer Lee",
    company: "Apex Manufacturing",
    email: "jlee@apex.com",
    linkedin: "https://linkedin.com/in/jenniferlee",
    whatsapp: "+12025550189",
    twitter: null,
    instagram: null,
    facebook: null,
    status: "Replied",
    lastContact: "2023-03-23",
    lastContacted: "2023-03-23",
    currentStage: "Replied",
    assignedTo: "Sarah Lee"
  },
  {
    id: 3,
    name: "Robert Johnson",
    company: "Global Products Ltd",
    email: "rjohnson@globalproducts.com",
    linkedin: "https://linkedin.com/in/robertjohnson",
    whatsapp: null,
    twitter: null,
    instagram: null,
    facebook: "https://facebook.com/robertjohnson",
    status: "Not Contacted",
    lastContact: "",
    lastContacted: "",
    currentStage: "Not Contacted",
    assignedTo: "Alex Chen"
  },
  {
    id: 4,
    name: "Patricia Williams",
    company: "First Choice Solutions",
    email: "pwilliams@firstchoice.com",
    linkedin: "https://linkedin.com/in/patriciawilliams",
    whatsapp: null,
    twitter: null,
    instagram: null,
    facebook: null,
    status: "Positive",
    lastContact: "2023-03-24",
    lastContacted: "2023-03-24",
    currentStage: "Positive",
    assignedTo: "John Smith"
  },
  {
    id: 5,
    name: "David Brown",
    company: "Summit Industries",
    email: "dbrown@summit.com",
    linkedin: "https://linkedin.com/in/davidbrown",
    whatsapp: null,
    twitter: "@davidb",
    instagram: null,
    facebook: null,
    status: "Contacted",
    lastContact: "2023-03-21",
    lastContacted: "2023-03-21",
    currentStage: "Contacted",
    assignedTo: "Mia Johnson"
  },
  {
    id: 6,
    name: "Elizabeth Davis",
    company: "CoreTech Systems",
    email: "edavis@coretech.com",
    linkedin: "https://linkedin.com/in/elizabethdavis",
    whatsapp: "+12025550134",
    twitter: null,
    instagram: null,
    facebook: null,
    status: "Follow-Up Needed",
    lastContact: "2023-03-20",
    lastContacted: "2023-03-20",
    currentStage: "Follow-Up Needed",
    assignedTo: "Sarah Lee"
  },
  {
    id: 7,
    name: "Thomas Miller",
    company: "Precision Manufacturing",
    email: "tmiller@precision.com",
    linkedin: "https://linkedin.com/in/thomasmiller",
    whatsapp: null,
    twitter: null,
    instagram: null,
    facebook: null,
    status: "Negative",
    lastContact: "2023-03-19",
    lastContacted: "2023-03-19",
    currentStage: "Negative",
    assignedTo: "Alex Chen"
  },
  {
    id: 8,
    name: "Sarah Wilson",
    company: "Innovative Solutions",
    email: "swilson@innovative.com",
    linkedin: "https://linkedin.com/in/sarahwilson",
    whatsapp: null,
    twitter: null,
    instagram: "@sarahw",
    facebook: null,
    status: "Replied",
    lastContact: "2023-03-23",
    lastContacted: "2023-03-23",
    currentStage: "Replied",
    assignedTo: "Mia Johnson"
  },
  {
    id: 9,
    name: "James Taylor",
    company: "Strategic Partners Inc",
    email: "jtaylor@strategic.com",
    linkedin: "https://linkedin.com/in/jamestaylor",
    whatsapp: null,
    twitter: null,
    instagram: null,
    facebook: null,
    status: "Not Contacted",
    lastContact: "",
    lastContacted: "",
    currentStage: "Not Contacted",
    assignedTo: "John Smith"
  },
  {
    id: 10,
    name: "Mary Anderson",
    company: "Elite Manufacturing",
    email: "manderson@elite.com",
    linkedin: "https://linkedin.com/in/maryanderson",
    whatsapp: "+12025550142",
    twitter: null,
    instagram: null,
    facebook: null,
    status: "Contacted",
    lastContact: "2023-03-22",
    lastContacted: "2023-03-22",
    currentStage: "Contacted",
    assignedTo: "Sarah Lee"
  }
];
